### PR TITLE
Criteria finder

### PR DESCRIPTION
**Pull request by agalamatis**
Small lambda to add new criteria in the database, so we don't need to define them twice and call populate, only s3_deploy. I haven't added yet to s3_deploy, waiting verification.

### CODE REVIEW

**Comment by agalamatis** [comment]
Added three more criteria and refined the lambda.

**Comment by danjoneslf** [comment]
I think if you do add a check whether active criteria exist in the code that should set active=False rather than delete the criteria. That way we maintain the indexes against any audits that have run with those criteria previously.

**Comment by agalamatis** [comment]
Will do and reopen the PR.

**Comment by agalamatis** [comment]
Ready to deploy on production.

**Comment by agalamatis** [comment]
And HTML strings pulled into the relevant descriptions, whys and hows of the criteria.

**Pull request merged**
