### PR TITLE
Improve prompts

### PR DESCRIPTION
**Pull request by akinnane**

### CODE REVIEW

**Comment by 0atman** [comment]
Y'all need standard.js 🙏

**Comment by 0atman** [comment]
I can be helpful too:
```js
var prompt = "Please enter the path to the ssh public key file:";
var prompt = "Please enter the local path to the public key file for the previous AWS key pair:";
```
Is the change.

**My review**

- It's improved some wording, but to my eyes has removed key information too. (why not say _ssh public key_?)
 - _"local"_ to what box? Could we need to be more specific to help our colleagues out?
 - With no context, I'm pretty sure that `var` should be `const`, but that sounds outside the scope of this PR

**Comment by 0atman** [comment]
My thinking about `var` vs `const` is similar to my think about `==` ver `===`. The former no longer exists in my code.

**Comment by akinnane** [comment]
I'm not keen on improving the promts any more as they are used in an expect script as part of the concourse pipeline :(.

We will have to revisit these once we have got rid of those.

Thanks for the suggestions @0atman!

**Comment by 0atman** [comment]
[BOARD EXPLANATION](https://trello.com/c/HLv8SxVP/1-board-explanation)

**Comment by akinnane** [comment]
This is old.

**Pull request closed without merging**
